-- Insert all 45 Organizations
USE local_youth_development_db;

INSERT INTO organizations (name, category, barangay, adviser_phone, adviser_email, is_active) VALUES
('LSPU SCC - Florence Nightingale''s Club', 'School Organization', 'Bubukal', '09216059887', 'florence.nightingale.lspu@gmail.com', 1),
('BARKADA KONTRA DROGA (BKD) of Governor. Felicisimo T. San Luis Integrated Senior High School', 'School Organization', 'Bubukal', '09363007278', 'bkdgftsishs@gmail.com', 1),
('Tinig ng mga Iskolar na Nagpapahayag ng Talino at Anyo - TINTA', 'School Organization', 'Bubukal', '09198870082', 'tintaorganization@gmail.com', 1),
('Senior Secondary Learner Government - Southbay Montessori School and Colleges, Inc.', 'School Organization', 'Pagsawitan', '09053160942', 'sslgofsbrmsci@gmail.com', 1),
('Junior Philippine Society of Public Administration – LSPU Santa Cruz Main Campus', 'School Organization', 'Bubukal', '09216886938', 'jpspalspuscc.official@gmail.com', 1),
('Pedro Guevara Memorial National High School - (CACHET) Campaign for Character Education and Tenacity ni Pedro Organization', 'School Organization', 'Barangay I (Pob.)', '09682938622', 'Cachetnipedropgmnhs@gmail.com', 1),
('Senior High School - Supreme Student Council GFTSLSHS', 'School Organization', 'Bubukal', '09500923851', 'Christarose.coloma@gmail.com', 1),
('Young Entrepreneurs Society Laguna State Polytechnic University-Main Campus', 'School Organization', 'Bubukal', '09620882991', 'cbaa.yes.organization@gmail.com', 1),
('Youth of Iglesia Filipina Independiente - Gatid (YIFI GATID)', 'Religious Organization', 'Gatid', '09994463032', 'lupenathaniel@gmail.com', 1),
('Junior Philippine Institute of Accountants LSPU - SCC', 'School Organization', 'Bubukal', '09956428537', 'lspusccbsa@gmail.com', 1),
('Laguna University - Young Entrepreneurs Society', 'School Organization', 'Calios', '09770077455', 'luyesorg2023@gmail.com', 1),
('SITIO YOUTH ORGANIZATION OF BAGUMBAYAN', 'Community Organization', 'Bagumbayan', '0', 'syo.bagumbayan@gmail.com', 1),
('SAMAHAN NG MGA INDIBIDWAL NA KASANGKA SA PAGLAGO NG ATING BAYAN-KABATAAN', 'Community Organization', 'Barangay III (Pob.)', '09295672456', 'jamesivandomingo@gmail.com', 1),
('Pedro Guevara Memorial National High School - Kabataang Pangarap ni Rizal (KAPARIZ)', 'School Organization', 'Barangay I (Pob.)', '09666021739', 'kapariz.pgmnhs@gmail.com', 1),
('GFTSISHS SCHOOLS STUDENT LEADERSHIP GOVERNMENT - SSLG', 'School Organization', 'Bubukal', '09859364457', 'govftsslg123@gmail.com', 1),
('Sining Kalinangan Cultural Troupe - Mananayaw ni Teddy', 'Cultural Organization', 'Calios', '09755744139', 'siningkalinanganculturaltroupe@gmail.com', 1),
('Pedro Guevara Memorial National High School - Youth for Environment in Schools Organization', 'School Organization', 'Barangay I (Pob.)', '09684966499', 'yesopgmnhs22@gmail.com', 1),
('Southbay Montessori School and College, Inc. - Student Government Organization', 'School Organization', 'Pagsawitan', '09351444469', 'sbmscisgo@gmail.com', 1),
('JUNIOR FINANCIAL EXECUTIVES', 'School Organization', 'Bubukal', '09765418606', 'jfinexlspuscc@gmail.com', 1),
('LSHS - Supreme Secondary Learner Government', 'School Organization', 'Barangay I (Pob.)', '09296662473', 'anthoniacorazoncadapan@gmail.com', 1),
('Broadcasting Society', 'School Organization', 'Bubukal', '09167662347', 'broadsoc.official@gmail.com', 1),
('SkillBuilders Club (GFTSISHS - TLE Department)', 'School Organization', 'Bubukal', '09684966241', 'ederlyn.delena@deped.gov.ph', 1),
('Kabataang Alay ay Paglilingkod ng Walang Alinlangan', 'School Organization', 'Barangay I (Pob.)', '09543491129', 'pgmnhskapwa@gmail.com', 1),
('Pedro Guevara Memorial National High School - Young Historians'' Club', 'School Organization', 'Barangay III (Pob.)', '09068645271', 'younghistoriansclub@gmail.com', 1),
('Laguna Senior High School - Youth for Environment in Schools Organization', 'School Organization', 'Barangay I (Pob.)', '09071055935', 'lianbryceamoranto256@gmail.com', 1),
('Rotaract Club of Sta. Cruz Pioneer', 'Service Organization', 'Patimbao', '09166583063', 'rotaractclubofsantacruzpioneer@gmail.com', 1),
('Humanities and Social Sciences Alliance of the Youth (HUSAY)', 'School Organization', 'Bubukal', '09972979352', 'humss.husayorganization@gmail.com', 1),
('Barkada Kontra Droga-Pedro Guevarra Memorial National High School', 'School Organization', 'Barangay I (Pob.)', '09952656002', 'bkdclub94@gmail.com', 1),
('Biological Sciences Society - LSPU SCC', 'School Organization', 'Bubukal', '09471904075', 'biologicalsocietylspuscc@gmail.com', 1),
('SPEAK YOUTH FOR JESUS MOVEMENT - SYJM', 'Religious Organization', 'Bubukal', '09267362117', 'speaksyjm@gmail.com', 1),
('Sta.Cruz/Pagsanjan Community Based Scouting', 'Community Organization', 'Bagumbayan', '09276333065', 'spcbscouting@gmail.com', 1),
('Pedro Guevara Memorial National High School - English and Forensic Club', 'School Organization', 'Barangay I (Pob.)', '09159461356', 'noelleantonettesoriano@gmail.com', 1),
('Laguna University - Accounting Information System Society', 'School Organization', 'Bubukal', '09543018851', 'lagunauniversityaissoc@gmail.com', 1),
('ARROWS-CAMPUS MINISTRY of Gov Felicisimo T San Luis Integrated Senior High School', 'School Organization', 'Bubukal', '09363007278', 'gftsishscampusministryarrows@gmail.com', 1),
('Interact Club of Southbay Montessori School and Colleges, Inc.', 'School Organization', 'Pagsawitan', '09362632018', 'interactclubsbmsci@gmail.com', 1),
('Pedro Guevara Memorial National High School - Ang Lagunian', 'School Organization', 'Barangay III (Pob.)', '09291824330', 'pedroguevaramnhsanglagunian@gmail.com', 1),
('Youth of Iglesia Filipina Independiente', 'Religious Organization', 'Bagumbayan', '09650379647', 'yifibagumbayan2019@gmail.com', 1),
('Pedro Guevara Memorial National High - The Lagunian School', 'School Organization', 'Barangay I (Pob.)', '09158402501', 'thelagunian.pgmnhs@gmail.com', 1),
('Pedro Guevara Memorial National High School - Supreme Secondary Learner Government', 'School Organization', 'Barangay III (Pob.)', '099842662870', 'pgmnhssslg@gmail.com', 1),
('Felisician Researchers to Empower Students and Promote Health and Well-being in the Educational Environment Organization (FRESH ORG)', 'School Organization', 'Bubukal', '09105700965', 'freshgft51@gmail.com', 1),
('JUNIOR MARKETING ASSOCIATION OF THE PHILIPPINES - LSPU STA. CRUZ CAMPUS', 'School Organization', 'Bubukal', '09173288813', 'jmaplspuscc@gmail.com', 1),
('Science Technology Engineering and Mathematics GFTSLISHS', 'School Organization', 'Bubukal', '09519104372', 'Johnrick292008@gmail.com', 1),
('Young Technologists'' Club (YTC)', 'School Organization', 'Barangay I (Pob.)', '09456622120', 'annalynbuenaventura31@gmail.com', 1),
('Criminal Justice Education Society (CJES)', 'School Organization', 'Bubukal', '09291218398', 'criminaljusticeeducationsociet@gmail.com', 1),
('New Gen Volleyball Club', 'Sports Organization', 'Patimbao', '09', 'newgenvolleyballclub1@gmail.com', 1);
